name: Build and Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install flake8

      - name: Run Linter
        run: flake8 health_check.py

      - name: Build Docker Image
        run: docker build -t health-tool .
